import streamlit as st
from llm import llm
from graph import graph
#Create the Cypher Prompt Template
from langchain.prompts.prompt import PromptTemplate
from langchain_community.chains.graph_qa.cypher import GraphCypherQAChain
CYPHER_GENERATION_TEMPLATE = """
You are an expert Neo4j Developer translating user questions into Cypher to answer questions about movies and provide recommendations.
Convert the user's question based on the schema.

Use only the provided relationship types and properties in the schema.
Do not use any other relationship types or properties that are not provided.
When using a parameter userId, make sure that the id is in quotes/ is a string value                                        

Do not return entire nodes or embedding properties.

Fine Tuning:

For movie titles that begin with "The", move "the" to the end. For example "The 39 Steps" becomes "39 Steps, The" or "the matrix" becomes "Matrix, The".

Example Cypher Statements:
Remember RETURN can only be used at the end of a query!

1. To find who acted in a movie:
```
MATCH (p:Person)-[r:ACTED_IN]->(m:Movie {{title: "Movie Title"}})
RETURN p.name, r.role
```

2. To find who directed a movie:
```
MATCH (p:Person)-[r:DIRECTED]->(m:Movie {{title: "Movie Title"}})
RETURN p.name
```
3. To find the actors and directors of a movie:
```
MATCH (m:Movie {{title: "Movie Title"}})
OPTIONAL MATCH (m)<-[:DIRECTED]-(d:Person)
OPTIONAL MATCH (m)<-[:ACTED_IN]-(a:Person)
RETURN m.title AS movie,
       collect(DISTINCT d.name) AS directors,
       collect(DISTINCT a.name) AS actors
```

4. How to find how many degrees of separation there are between two people:
```
MATCH path = shortestPath(
  (p1:Person {{name: "Actor 1"}})-[:ACTED_IN|DIRECTED*]-(p2:Person {{name: "Actor 2"}})
)
WITH path, p1, p2, relationships(path) AS rels
RETURN
  p1 {{ .name, .born, link:'https://www.themoviedb.org/person/'+ p1.tmdbId }} AS start,
  p2 {{ .name, .born, link:'https://www.themoviedb.org/person/'+ p2.tmdbId }} AS end,
  reduce(output = '', i in range(0, length(path)-1) |
    output + CASE
      WHEN i = 0 THEN
       startNode(rels[i]).name + CASE WHEN type(rels[i]) = 'ACTED_IN' THEN ' played '+ rels[i].role +' in 'ELSE ' directed ' END + endNode(rels[i]).title
       ELSE
         ' with '+ startNode(rels[i]).name + ', who '+ CASE WHEN type(rels[i]) = 'ACTED_IN' THEN 'played '+ rels[i].role +' in '
    ELSE 'directed '
      END + endNode(rels[i]).title
      END
  ) AS pathBetweenPeople

```
5. To find a movie given a Genre and highly rated:
```
MATCH (m:Movie)-[r:IN_GENRE]->(:Genre {{name: "Genre"}})
WHERE m.imdbRating > 7.5
RETURN m.title
```

Schema:
{schema}

Question:
{question}
"""
def format_result(result) -> dict:
    """
    Formats Neo4j query results into a structure that's easy for LLMs to interpret.
    Handles nodes, relationships, lists, and properties.
    """
    # Check if the result is a string
    if isinstance(result, str):
        # If it's a string, return it as is
        return {"message": result}
    
    formatted_result = {}
    
    for key, value in result.items():
        if isinstance(value, dict):
            # If it's already a dictionary, return it as is
            formatted_result[key] = value
        elif isinstance(value, list):
            # If it's a list, format each item in the list
            formatted_result[key] = [format_entity(item) for item in value]
        else:
            # Format single entities (nodes, relationships, etc.)
            formatted_result[key] = format_entity(value)
    
    return formatted_result


def format_entity(entity):
    """
    Formats Neo4j entities (nodes, relationships, etc.) into a dictionary structure.
    """
    if hasattr(entity, "labels"):
        # It's a node
        return {
            "type": "node",
            "labels": list(entity.labels),
            "properties": dict(entity)
        }
    elif hasattr(entity, "type"):
        # It's a relationship
        return {
            "type": "relationship",
            "relationship_type": entity.type,
            "properties": dict(entity)
        }
    else:
        # It's a scalar value (e.g., string, number, etc.)
        return entity



cypher_prompt = PromptTemplate.from_template(CYPHER_GENERATION_TEMPLATE)

# Use the {user_id} to help answer the question based on the movies the user with the specified movies [{user_id}] has rated.
    # Set up the GraphCypherQAChain from the LangChain library
cypher_qa = GraphCypherQAChain.from_llm(
     llm=llm,
    graph=graph,
    verbose=True,
    validate_cypher=True,  # Validate the Cypher query before execution
    cypher_prompt=cypher_prompt  # Custom Cypher prompt for LLM
)


def run_query_with_langchain(query: str) -> dict:
    """
    Executes a Cypher query using LangChain's GraphCypherQAChain and returns the formatted results.
    """
    # Step 1: Run the Cypher query generated by the LLM
    raw_result = cypher_qa.invoke(query)
    
    # Debugging: Print the raw result to check its type
    print(f"Raw Result: {raw_result} (type: {type(raw_result)})")
    
    # Step 2: Check if raw_result is a string and handle it
    if isinstance(raw_result, str):
        # Return the raw string message if it's not a dictionary
        return {"message": raw_result}
    
    # Step 3: Format the raw result if it's a dictionary
    formatted_result = format_result(raw_result)
    
    return formatted_result


